In [8]:
import pandas as pd
import numpy as np
trades = [[10, 0, 20 ],
          [5, -20,-30],
          [5, 15, 10 ]]
prices = [[10, 13, 10],
          [8, 15, 25 ],
          [9, 12, 20 ]]
trades = np.array(trades)
prices = np.array(prices)
result = trades * prices #trades @ prices
print(result)
result = np.sum(result, axis=1)
print(result)

#so this represents deltas to the NAV
#not the same as the NAV
#i need to modify trades to be delta-driven
#still not exactly, we need to only align by rows... it's trickier, we only want the top left, mid, and bot right cell
#tho this seems to be just more like a dot product problem i think


[[ 100    0  200]
 [  40 -300 -750]
 [  45  180  200]]
[  300 -1010   425]


In [2]:
import pandas as pd

# Sample prices dataframe
prices_data = {
    'date': ['2023-07-01', '2023-07-02', '2023-07-03'],
    'ticker': ['AAPL', 'GOOG', 'AAPL'],
    'price': [150.0, 2800.0, 155.0]
}
prices = pd.DataFrame(prices_data)

# Sample trades dataframe
trades_data = {
    'date': ['2023-07-01', '2023-07-02', '2023-07-02'],
    'ticker': ['AAPL', 'GOOG', 'AAPL'],
    'quantity': [10, -5, -5]  # Negative quantity represents selling
}
trades = pd.DataFrame(trades_data)

# Step 1: Merge prices and trades dataframes
portfolio = pd.merge(prices, trades, on=['date', 'ticker'])

# Step 2: Calculate the value of each trade at the time it was made
portfolio['trade_value'] = portfolio['price'] * portfolio['quantity']

# Step 3: Calculate the total value of each holding at each point in time
portfolio['holding_value'] = portfolio.groupby(['ticker'])['trade_value'].cumsum()

# Step 4: Calculate the realized PnL
portfolio['realized_pnl'] = portfolio.groupby(['ticker'])['holding_value'].diff().fillna(0)

# Step 5: Calculate the unrealized PnL for open positions
portfolio['unrealized_pnl'] = (portfolio['price'] - portfolio['price'].shift(1)) * portfolio['quantity'].shift(1)

# Step 6: Combine the realized and unrealized PnL to get the total PnL
portfolio['total_pnl'] = portfolio['realized_pnl'] + portfolio['unrealized_pnl']

# Final dataframe showing PnL for each trade and overall portfolio PnL
print(prices)
print(trades)
print(portfolio)

         date ticker   price
0  2023-07-01   AAPL   150.0
1  2023-07-02   GOOG  2800.0
2  2023-07-03   AAPL   155.0
         date ticker  quantity
0  2023-07-01   AAPL        10
1  2023-07-02   GOOG        -5
2  2023-07-02   AAPL        -5
         date ticker   price  quantity  trade_value  holding_value  \
0  2023-07-01   AAPL   150.0        10       1500.0         1500.0   
1  2023-07-02   GOOG  2800.0        -5     -14000.0       -14000.0   

   realized_pnl  unrealized_pnl  total_pnl  
0           0.0             NaN        NaN  
1           0.0         26500.0    26500.0  
